FROM python:3.11-slim

WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential libpq-dev \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy entire project
COPY . .

# Redis URL (used by django-rq)
ENV REDIS_URL=redis://host.docker.internal:6379/0

# Start RQ worker (your queue name can differ)
CMD ["python", "manage.py", "rqworker", "default"]

