FROM webrecorder/pywb:latest

WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential libpq-dev docker-cli \
    libisal2 maven cargo rustc poppler-utils
    && rm -rf /var/lib/apt/lists/*

# Oracle JDK 26
RUN wget -O /tmp/jdk-26_linux-x64_bin.deb \
    https://download.oracle.com/java/26/latest/jdk-26_linux-x64_bin.deb \
    && apt-get update \
    && apt-get install -y /tmp/jdk-26_linux-x64_bin.deb \
    && rm /tmp/jdk-26_linux-x64_bin.deb

ENV JAVA_HOME=/usr/lib/jvm/jdk-26.0.2-oracle-x64
ENV PATH="${JAVA_HOME}/bin:${PATH}"

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy entire project
COPY . .

# Build Java project
WORKDIR /app/warc2se
RUN mvn -B clean package -DskipTests

WORKDIR /app

# Start RQ worker (your queue name can differ)
CMD ["python", "manage.py", "rqworker", "crawls"]

