# Generated by Django 5.2.8 on 2025-12-17 21:52

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CrawlConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parentId', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('disabled', 'Disabled'), ('restricted', 'Restricted'), ('predefined', 'Predefined'), ('custom', 'Custom')], max_length=32)),
                ('crawlEngine', models.CharField(max_length=64)),
                ('yamlConfig', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='GlobalConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255, unique=True)),
                ('value', models.TextField(blank=True, null=True)),
                ('entry_class', models.CharField(choices=[('global', 'Global'), ('restricted', 'Restricted'), ('system', 'System')], default='global', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parentId', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ScheduleConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parentId', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('disabled', 'Disabled'), ('restricted', 'Restricted'), ('predefined', 'Predefined'), ('custom', 'Custom')], max_length=32)),
                ('yamlConfig', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='WebsiteCrawlParameters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope_type', models.CharField(choices=[('prefix', 'Prefix (URL prefix)'), ('domain', 'Domain'), ('host', 'Host')], default='domain', max_length=16)),
                ('generate_cdx', models.BooleanField(default=True)),
                ('workers', models.PositiveIntegerField(default=32)),
                ('page_load_timeout', models.PositiveIntegerField(default=25)),
                ('disk_utilization', models.PositiveIntegerField(default=0)),
                ('time_limit', models.PositiveIntegerField(default=86400)),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True)),
                ('is_default', models.BooleanField(default=False)),
                ('start_urls', django.contrib.postgres.fields.ArrayField(base_field=models.URLField(), default=list, help_text='Seed URLs (Browsertrix: seeds)', size=None)),
                ('include_linked', models.BooleanField(default=False, help_text='Include linked pages (Page List crawls)')),
                ('max_depth', models.PositiveIntegerField(blank=True, help_text='Crawl depth', null=True)),
                ('url_prefixes', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=512), blank=True, default=list, help_text='Regex URL prefixes to include', size=None)),
                ('additional_pages', django.contrib.postgres.fields.ArrayField(base_field=models.URLField(), blank=True, default=list, help_text='Extra pages outside crawl scope', size=None)),
                ('exclude_text_matches', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=256), blank=True, default=list, help_text='Exclude URLs containing text', size=None)),
                ('exclude_regex_matches', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=512), blank=True, default=list, help_text='Exclude URLs matching regex', size=None)),
                ('max_pages', models.PositiveIntegerField(blank=True, help_text='Maximum number of pages', null=True)),
                ('size_limit_gb', models.FloatField(blank=True, help_text='Maximum crawl size (GB)', null=True)),
                ('auto_scroll', models.BooleanField(default=True)),
                ('auto_click', models.BooleanField(default=False)),
                ('post_load_delay_ms', models.PositiveIntegerField(default=0)),
                ('page_extra_delay_ms', models.PositiveIntegerField(default=0)),
                ('user_agent', models.CharField(blank=True, max_length=256)),
                ('language', models.CharField(blank=True, help_text='ISO 639[-country] code', max_length=32)),
                ('proxy_server', models.CharField(blank=True, max_length=256)),
                ('extra_config', models.JSONField(blank=True, default=dict, help_text='Raw Browsertrix YAML extensions (use only if needed)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Snapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('finished', 'Finished'), ('failed', 'Failed'), ('accepted', 'Accepted'), ('published', 'Published')], default='queued', max_length=20)),
                ('progress', models.FloatField(default=0.0)),
                ('stats', models.JSONField(blank=True, default=dict)),
                ('machine', models.CharField(blank=True, max_length=255, null=True)),
                ('error', models.TextField(blank=True, null=True)),
                ('published', models.BooleanField(default=False)),
                ('auto_update', models.BooleanField(default=False)),
                ('result', models.JSONField(blank=True, default=dict)),
                ('rq_job_id', models.CharField(blank=True, max_length=255, null=True)),
                ('isDeleted', models.BooleanField(default=False)),
                ('publicationStatus', models.CharField(blank=True, choices=[('INTERNAL', 'internal'), ('PUBLIC', 'public')], max_length=32, null=True)),
                ('crawlStartTimestamp', models.DateTimeField(blank=True, null=True)),
                ('crawlStopTimestamp', models.DateTimeField(blank=True, null=True)),
                ('size', models.BigIntegerField(blank=True, null=True)),
                ('itemCount', models.BigIntegerField(blank=True, null=True)),
                ('warcPath', models.CharField(blank=True, max_length=512, null=True)),
                ('replayCollectionId', models.CharField(blank=True, max_length=255, null=True)),
                ('process_id', models.CharField(blank=True, max_length=64, null=True)),
                ('process_stats', models.JSONField(blank=True, default=dict, help_text='Docker-level runtime statistics for the crawl container')),
                ('crawl_stats', models.JSONField(blank=True, help_text='Aggregated crawl statistics and health metrics', null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=64)),
                ('uid', models.CharField(max_length=128)),
                ('user', models.CharField(max_length=128)),
                ('scheduleTime', models.DateTimeField(blank=True, null=True)),
                ('startTime', models.DateTimeField(auto_now_add=True)),
                ('updateTime', models.DateTimeField(auto_now=True)),
                ('updateMessage', models.TextField(blank=True, null=True)),
                ('finishTime', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('created', 'Created'), ('scheduled', 'Scheduled'), ('cancelled', 'Cancelled'), ('running', 'Running'), ('success', 'Success'), ('failed', 'Failed')], max_length=32)),
                ('result', models.TextField(blank=True, null=True)),
                ('resultDescription', models.TextField(blank=True, null=True)),
                ('runData', models.TextField(blank=True, null=True)),
                ('priority', models.CharField(default='normal', max_length=32)),
                ('schedule', models.CharField(blank=True, max_length=64, null=True)),
                ('taskParameters', models.JSONField(blank=True, null=True)),
                ('taskResponse', models.JSONField(blank=True, null=True)),
                ('snapshot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task', to='archiver.snapshot')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=64, null=True)),
                ('emailActivated', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('request', 'Request'), ('active', 'Active'), ('suspended', 'Suspended'), ('closed', 'Closed')], default='request', max_length=32)),
                ('organisation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='archiver.organisation')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('isDeleted', models.BooleanField(default=False)),
                ('auto_publish', models.BooleanField(default=False)),
                ('displayName', models.CharField(blank=True, max_length=255, null=True)),
                ('shortDescription', models.TextField(blank=True, null=True)),
                ('longDescription', models.TextField(blank=True, null=True)),
                ('doCrawl', models.BooleanField(default=True)),
                ('suspendCrawlUntilTimestamp', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scope_type', models.CharField(blank=True, choices=[('prefix', 'Prefix (URL prefix)'), ('domain', 'Domain'), ('host', 'Host')], help_text='Optional override. If empty → uses global defaults.', max_length=16, null=True)),
                ('generate_cdx', models.BooleanField(blank=True, null=True)),
                ('workers', models.PositiveIntegerField(default=1)),
                ('page_load_timeout', models.PositiveIntegerField(default=60)),
                ('disk_utilization', models.PositiveIntegerField(default=0)),
                ('time_limit', models.PositiveIntegerField(default=86400)),
                ('enabled', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='websites', to='archiver.organisation')),
                ('tags', models.ManyToManyField(blank=True, to='archiver.tag')),
                ('website_crawl_parameters', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='website_crawl_parameters', to='archiver.websitecrawlparameters')),
            ],
        ),
        migrations.AddField(
            model_name='snapshot',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='archiver.website'),
        ),
        migrations.CreateModel(
            name='WebsiteGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('websites', models.ManyToManyField(to='archiver.website')),
            ],
        ),
        migrations.CreateModel(
            name='Warc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=512)),
                ('path', models.TextField()),
                ('size_bytes', models.BigIntegerField()),
                ('created_at', models.DateTimeField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warcs', to='archiver.snapshot')),
            ],
            options={
                'unique_together': {('snapshot', 'filename')},
            },
        ),
    ]
