# Generated by Django 5.2.8 on 2025-12-10 12:05

import django.contrib.postgres.fields
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('threadId', models.IntegerField()),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('userId', models.IntegerField()),
                ('body', models.TextField()),
                ('entryClass', models.CharField(choices=[('public', 'Public'), ('private', 'Private'), ('history', 'History'), ('history_hidden', 'History Hidden'), ('system', 'System'), ('log', 'Log')], max_length=20)),
                ('entryLevel', models.CharField(choices=[('none', 'None'), ('debug', 'Debug'), ('info', 'Info'), ('warning', 'Warning'), ('error', 'Error'), ('alert', 'Alert')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='CommentThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accessMode', models.CharField(max_length=20)),
                ('entityType', models.CharField(max_length=32)),
                ('entityId', models.IntegerField()),
                ('messages', models.IntegerField(default=0)),
                ('lastTimestamp', models.DateTimeField(blank=True, null=True)),
                ('lastAuthor', models.IntegerField(blank=True, null=True)),
                ('lastMessage', models.TextField(blank=True, null=True)),
                ('lastType', models.CharField(blank=True, max_length=32, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CrawlConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parentId', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('disabled', 'Disabled'), ('restricted', 'Restricted'), ('predefined', 'Predefined'), ('custom', 'Custom')], max_length=32)),
                ('crawlEngine', models.CharField(max_length=64)),
                ('yamlConfig', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='GlobalConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255, unique=True)),
                ('value', models.TextField(blank=True, null=True)),
                ('entry_class', models.CharField(choices=[('global', 'Global'), ('restricted', 'Restricted'), ('system', 'System')], default='global', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='MetadataEntryString',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255)),
                ('value', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parentId', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ScheduleConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parentId', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('disabled', 'Disabled'), ('restricted', 'Restricted'), ('predefined', 'Predefined'), ('custom', 'Custom')], max_length=32)),
                ('yamlConfig', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=64)),
                ('uid', models.CharField(max_length=128)),
                ('user', models.CharField(max_length=128)),
                ('scheduleTime', models.DateTimeField(blank=True, null=True)),
                ('startTime', models.DateTimeField(blank=True, null=True)),
                ('updateTime', models.DateTimeField(blank=True, null=True)),
                ('updateMessage', models.TextField(blank=True, null=True)),
                ('finishTime', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('cancelled', 'Cancelled'), ('running', 'Running'), ('success', 'Success'), ('failed', 'Failed')], max_length=32)),
                ('result', models.TextField(blank=True, null=True)),
                ('resultDescription', models.TextField(blank=True, null=True)),
                ('runData', models.TextField(blank=True, null=True)),
                ('priority', models.CharField(default='normal', max_length=32)),
                ('schedule', models.CharField(blank=True, max_length=64, null=True)),
                ('taskParameters', models.JSONField(blank=True, null=True)),
                ('taskResponse', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WebsiteCrawlParameters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope_type', models.CharField(choices=[('prefix', 'Prefix (URL prefix)'), ('domain', 'Domain'), ('host', 'Host')], default='domain', max_length=16)),
                ('generate_cdx', models.BooleanField(default=True)),
                ('workers', models.PositiveIntegerField(default=32)),
                ('page_load_timeout', models.PositiveIntegerField(default=25)),
                ('disk_utilization', models.PositiveIntegerField(default=0)),
                ('time_limit', models.PositiveIntegerField(default=86400)),
            ],
        ),
        migrations.CreateModel(
            name='MetadataArchivalWebsite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extra', models.ManyToManyField(blank=True, to='archiver.metadataentrystring')),
            ],
        ),
        migrations.CreateModel(
            name='MetadataArchivalSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extra', models.ManyToManyField(blank=True, to='archiver.metadataentrystring')),
            ],
        ),
        migrations.CreateModel(
            name='MetadataArchivalOrganisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extra', models.ManyToManyField(blank=True, to='archiver.metadataentrystring')),
            ],
        ),
        migrations.CreateModel(
            name='MetadataTechnicalOrganisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extra', models.ManyToManyField(blank=True, to='archiver.metadataentrystring')),
            ],
        ),
        migrations.CreateModel(
            name='MetadataTechnicalSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crawler', models.CharField(blank=True, max_length=255, null=True)),
                ('crawlerConfiguration', models.CharField(blank=True, max_length=255, null=True)),
                ('crawlerOutput', models.TextField(blank=True, null=True)),
                ('crawlWarcSize', models.BigIntegerField(blank=True, null=True)),
                ('warehousePointer', models.CharField(blank=True, max_length=255, null=True)),
                ('extra', models.ManyToManyField(blank=True, to='archiver.metadataentrystring')),
            ],
        ),
        migrations.CreateModel(
            name='MetadataTechnicalWebsite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extra', models.ManyToManyField(blank=True, to='archiver.metadataentrystring')),
            ],
        ),
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('header', models.TextField(blank=True, null=True)),
                ('footer', models.TextField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=False)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questionnaires', to='archiver.category')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('body', models.TextField(blank=True, null=True)),
                ('input', models.CharField(choices=[('text', 'Text'), ('textarea', 'Textarea'), ('radio', 'Radio'), ('checkbox', 'Checkbox'), ('select', 'Select'), ('date', 'Date'), ('number', 'Number')], max_length=20)),
                ('values', models.TextField(blank=True, help_text='Possible values (newline-separated)', null=True)),
                ('questionnaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='archiver.questionnaire')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=64, null=True)),
                ('emailActivated', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('request', 'Request'), ('active', 'Active'), ('suspended', 'Suspended'), ('closed', 'Closed')], default='request', max_length=32)),
                ('organisation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='archiver.organisation')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('isDeleted', models.BooleanField(default=False)),
                ('displayName', models.CharField(blank=True, max_length=255, null=True)),
                ('shortDescription', models.TextField(blank=True, null=True)),
                ('longDescription', models.TextField(blank=True, null=True)),
                ('doCrawl', models.BooleanField(default=True)),
                ('suspendCrawlUntilTimestamp', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scope_type', models.CharField(blank=True, choices=[('prefix', 'Prefix (URL prefix)'), ('domain', 'Domain'), ('host', 'Host')], help_text='Optional override. If empty → uses global defaults.', max_length=16, null=True)),
                ('generate_cdx', models.BooleanField(blank=True, null=True)),
                ('workers', models.PositiveIntegerField(default=1)),
                ('page_load_timeout', models.PositiveIntegerField(default=60)),
                ('disk_utilization', models.PositiveIntegerField(default=0)),
                ('time_limit', models.PositiveIntegerField(default=86400)),
                ('enabled', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='websites', to='archiver.organisation')),
                ('tags', models.ManyToManyField(blank=True, to='archiver.tag')),
            ],
        ),
        migrations.CreateModel(
            name='Snapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('finished', 'Finished'), ('failed', 'Failed'), ('accepted', 'Accepted')], default='queued', max_length=20)),
                ('progress', models.FloatField(default=0.0)),
                ('stats', models.JSONField(blank=True, default=dict)),
                ('process_id', models.IntegerField(blank=True, null=True)),
                ('machine', models.CharField(blank=True, max_length=255, null=True)),
                ('error', models.TextField(blank=True, null=True)),
                ('accepted', models.BooleanField(default=False)),
                ('result', models.JSONField(blank=True, default=dict)),
                ('rq_job_id', models.CharField(blank=True, max_length=255, null=True)),
                ('isDeleted', models.BooleanField(default=False)),
                ('publicationStatus', models.CharField(blank=True, choices=[('INTERNAL', 'internal'), ('PUBLIC', 'public')], max_length=32, null=True)),
                ('crawlStartTimestamp', models.DateTimeField(blank=True, null=True)),
                ('crawlStopTimestamp', models.DateTimeField(blank=True, null=True)),
                ('size', models.BigIntegerField(blank=True, null=True)),
                ('itemCount', models.BigIntegerField(blank=True, null=True)),
                ('warcPath', models.CharField(blank=True, max_length=512, null=True)),
                ('replayCollectionId', models.CharField(blank=True, max_length=255, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crawl_jobs', to='archiver.website')),
            ],
        ),
        migrations.CreateModel(
            name='WebsiteGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('websites', models.ManyToManyField(to='archiver.website')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionnaireResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organisation_id', models.BigIntegerField()),
                ('response', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=list, size=None)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('questionnaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='archiver.questionnaire')),
            ],
            options={
                'unique_together': {('organisation_id', 'questionnaire')},
            },
        ),
    ]
