# Generated by Django 5.2.8 on 2025-12-17 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archiver', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='user',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
