# Generated by Django 5.2.8 on 2025-12-17 23:42

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archiver', '0002_alter_task_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websitecrawlparameters',
            name='start_urls',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.URLField(), blank=True, default=list, help_text='Seed URLs (Browsertrix: seeds)', null=True, size=None),
        ),
    ]
