# Generated by Django 5.2.8 on 2025-12-18 08:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archiver', '0003_alter_websitecrawlparameters_start_urls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('created', 'Created'), ('scheduled', 'Scheduled'), ('cancelled', 'Cancelled'), ('running', 'Running'), ('success', 'Success'), ('failed', 'Failed'), ('paused', 'Paused')], max_length=32),
        ),
        migrations.CreateModel(
            name='TaskResponseDelivery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique delivery UUID (idempotency key)', primary_key=True, serialize=False)),
                ('payload', models.JSONField(help_text='Exact Task.taskResponse JSON sent')),
                ('target_url', models.URLField()),
                ('http_method', models.CharField(default='PUT', max_length=8)),
                ('http_status', models.PositiveIntegerField(blank=True, help_text='HTTP status returned by receiver', null=True)),
                ('response_body', models.TextField(blank=True, help_text='Raw response body (if any)')),
                ('success', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True, help_text='Network / exception error (if any)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='response_deliveries', to='archiver.task')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['task'], name='archiver_ta_task_id_54ebfe_idx'), models.Index(fields=['success'], name='archiver_ta_success_931886_idx')],
            },
        ),
    ]
