# Generated by Django 6.0 on 2025-12-19 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archiver', '0004_alter_task_status_taskresponsedelivery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('scheduled', 'Scheduled'), ('cancelled', 'Cancelled'), ('running', 'Running'), ('success', 'Success'), ('failed', 'Failed'), ('paused', 'Paused')], max_length=32),
        ),
        migrations.AlterField(
            model_name='task',
            name='uid',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
