# Generated by Django 6.0 on 2025-12-20 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archiver', '0005_alter_task_status_alter_task_uid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warc',
            name='created',
        ),
        migrations.AddField(
            model_name='warc',
            name='sha256',
            field=models.CharField(default=12345, max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='websitecrawlparameters',
            name='engine_type',
            field=models.CharField(choices=[('browsertrix', 'Browsertrix'), ('heritrix', 'Heritrix')], default='browsertrix', max_length=32),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task',
            name='snapshot',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task', to='archiver.snapshot'),
        ),
        migrations.AlterField(
            model_name='warc',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
