# Generated by Django 6.0 on 2025-12-20 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archiver', '0006_remove_warc_created_warc_sha256_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websitecrawlparameters',
            name='scope_type',
            field=models.CharField(choices=[('prefix', 'Prefix (URL prefix)'), ('domain', 'Domain'), ('host', 'Host')], default='page', max_length=16),
        ),
    ]
