# Generated by Django 6.0 on 2025-12-20 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archiver', '0007_alter_websitecrawlparameters_scope_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snapshot',
            name='publicationStatus',
            field=models.CharField(blank=True, choices=[('internal', 'internal'), ('public', 'public')], max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='snapshot',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('crawling', 'Crawling'), ('suspended', 'Suspended'), ('stopped', 'Stopped'), ('completed', 'Completed'), ('failed', 'Failed'), ('deleted', 'Deleted'), ('published', 'Published')], default='queued', max_length=20),
        ),
        migrations.AlterField(
            model_name='website',
            name='scope_type',
            field=models.CharField(blank=True, choices=[('prefix', 'Prefix (URL prefix)'), ('domain', 'Domain'), ('host', 'Host'), ('page', 'Page')], help_text='Optional override. If empty → uses global defaults.', max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='websitecrawlparameters',
            name='scope_type',
            field=models.CharField(choices=[('prefix', 'Prefix (URL prefix)'), ('domain', 'Domain'), ('host', 'Host'), ('page', 'Page')], default='page', max_length=16),
        ),
    ]
