# Generated by Django 6.0 on 2025-12-20 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archiver', '0008_alter_snapshot_publicationstatus_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snapshot',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('crawling', 'Crawling'), ('suspended', 'Suspended'), ('stopped', 'Stopped'), ('completed', 'Completed'), ('failed', 'Failed'), ('deleted', 'Deleted'), ('published', 'Published')], default='pending', max_length=20),
        ),
    ]
