# Generated by Django 6.0 on 2025-12-20 15:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archiver', '0009_alter_snapshot_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='snapshot',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique delivery UUID (idempotency key)'),
        ),
    ]
