# Generated by Django 6.0 on 2025-12-21 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archiver', '0011_alter_snapshot_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snapshot',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='archiver.website'),
        ),
    ]
