# Generated by Django 6.0 on 2025-12-22 11:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archiver', '0010_snapshot_uid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='snapshot',
            old_name='itemCount',
            new_name='item_count',
        ),
        migrations.RenameField(
            model_name='snapshot',
            old_name='publicationStatus',
            new_name='publication_status',
        ),
        migrations.RenameField(
            model_name='snapshot',
            old_name='replayCollectionId',
            new_name='replay_collection_id',
        ),
        migrations.RenameField(
            model_name='snapshot',
            old_name='warcPath',
            new_name='warc_path',
        ),
        migrations.RenameField(
            model_name='taskresponsedelivery',
            old_name='id',
            new_name='uid',
        ),
        migrations.AddField(
            model_name='warc',
            name='is_production',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('cancelled', 'Cancelled'), ('running', 'Running'), ('paused', 'Paused'), ('success', 'Success'), ('failed', 'Failed')], default='scheduled', max_length=32),
        ),

        migrations.DeleteModel(
            name="TaskResponseDelivery",
        ),

    ]
