# Generated by Django 6.0 on 2025-12-22 11:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archiver', '0013_rename_itemcount_snapshot_item_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='id',
        ),
        migrations.AlterField(
            model_name='task',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='TaskResponseDelivery',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique delivery UUID (idempotency key)', primary_key=True, serialize=False)),
                ('payload', models.JSONField()),
                ('target_url', models.URLField()),
                ('http_method', models.CharField(default='PUT', max_length=8)),
                ('http_status', models.PositiveIntegerField(blank=True, help_text='HTTP status returned by receiver', null=True)),
                ('response_body', models.TextField(blank=True, help_text='Raw response body (if any)')),
                ('success', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True, help_text='Network / exception error (if any)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='response_deliveries', to='archiver.task')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['task'], name='archiver_ta_task_id_54ebfe_idx'), models.Index(fields=['success'], name='archiver_ta_success_931886_idx')],
            },
        ),
    ]
