# Generated by Django 6.0 on 2025-12-22 12:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archiver', '0014_remove_task_id_alter_task_uid_taskresponsedelivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task',
            name='startTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
