# Generated by Django 6.0 on 2025-12-22 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archiver', '0015_task_created_at_alter_task_starttime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='uid',
            field=models.CharField(max_length=128),
        ),
    ]
