# Generated by Django 6.0 on 2025-12-22 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archiver', '0017_alter_task_options_task_archiver_ta_uid_b34941_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='snapshot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task', to='archiver.snapshot'),
        ),
    ]
