# Generated by Django 6.0 on 2025-12-22 21:26

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archiver', '0018_alter_task_snapshot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snapshot',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique delivery UUID (idempotency key)', unique=True),
        ),
    ]
