# Generated by Django 6.0 on 2025-12-23 19:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archiver', '0019_alter_snapshot_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='snapshot',
            name='container_stats',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='snapshot',
            name='crawlWarcSize',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='snapshot',
            name='crawler',
            field=models.CharField(choices=[('browsertrix', 'Browsertrix'), ('heritrix', 'Heritrix')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='snapshot',
            name='crawlerConfiguration',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='snapshot',
            name='crawlerOutput',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='snapshot',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='snapshot',
            name='crawl_stats',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('scheduled', 'Scheduled'), ('cancelled', 'Cancelled'), ('running', 'Running'), ('paused', 'Paused'), ('success', 'Success'), ('failed', 'Failed')], default='scheduled', max_length=32),
        ),
        migrations.CreateModel(
            name='SnapshotResponseDelivery',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique delivery UUID (idempotency key)', primary_key=True, serialize=False)),
                ('payload', models.JSONField()),
                ('target_url', models.URLField()),
                ('http_method', models.CharField(max_length=8)),
                ('http_status', models.PositiveIntegerField(blank=True, help_text='HTTP status returned by receiver', null=True)),
                ('response_body', models.TextField(blank=True, help_text='Raw response body (if any)')),
                ('success', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True, help_text='Network / exception error (if any)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='response_deliveries', to='archiver.snapshot')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['snapshot'], name='archiver_sn_snapsho_eeb72f_idx'), models.Index(fields=['success'], name='archiver_sn_success_d89717_idx')],
            },
        ),
    ]
