# Generated by Django 6.0 on 2025-12-31 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archiver', '0020_snapshot_container_stats_snapshot_crawlwarcsize_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('low', 'low'), ('normal', 'normal'), ('high', 'high'), ('priority', 'priority')], default='normal', max_length=32),
        ),
    ]
