# Generated by Django 6.0 on 2026-01-11 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archiver', '0021_alter_task_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='snapshot',
            name='justification',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='justification',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('scheduled', 'Scheduled'), ('cancelled', 'Cancelled'), ('running', 'Running'), ('stopped', 'Stopped'), ('paused', 'Paused'), ('success', 'Success'), ('failed', 'Failed')], default='scheduled', max_length=32),
        ),
    ]
