# Generated by Django 6.0 on 2026-01-22 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archiver', '0022_snapshot_justification_task_justification_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='snapshot',
            old_name='justification',
            new_name='crawlJustification',
        ),
        migrations.RemoveField(
            model_name='task',
            name='justification',
        ),
        migrations.AddField(
            model_name='snapshot',
            name='publicationJustification',
            field=models.TextField(blank=True, null=True),
        ),
    ]
