# Generated by Django 6.0 on 2026-02-06 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archiver', '0023_rename_justification_snapshot_crawljustification_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websitecrawlparameters',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
