# Generated by Django 6.0 on 2026-02-10 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archiver', '0024_alter_websitecrawlparameters_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='snapshot',
            name='replayRelativeUrl',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
